services:
  db:
    networks:
      final: null
    volumes:
      - "./db:/db"
    container_name: SQLQA
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 3306:3306
    image: "mysql:8.0"
  #    command:
  #      - /db/setup.sh

  vk_api:
    networks:
      final: null
    container_name: vk_mock
    ports:
      - 8543:8543
    build: ./vk_mock/.

  myapp:
    networks:
      final: null
    volumes:
      - "./CONFIG:/myapp_config"
    container_name: myapp
    ports:
      - 8081:8081
    image: "myapp"
    entrypoint: /app/myapp --config=/myapp_config/myapp.conf
    depends_on:
      db:
        condition: service_started
      vk_api:
        condition: service_started

  selenoid:
    networks:
      final: null
    container_name: selenoid
    image: "aerokube/selenoid:latest-release"
    ports:
      - 4444:4444
    volumes:
      - "./selenoid_config:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./selenoid_config/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=./selenoid_config/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "final" ]

  selenoid-ui:
    networks:
      final: null
    container_name: selenoid-ui
    image: "aerokube/selenoid-ui"
    ports:
      - 8082:8080
    command: [ "--selenoid-uri", "http://selenoid:4444" ]

  ui-tests:
    networks:
      final: null
    image: "python_test:latest"
    container_name: ui-tests
    volumes:
      - "./tests/:/tests"
      - "./allure-report:/tmp/allure"
    entrypoint: bash /tests/start_tests.sh
    depends_on:
      selenoid:
        condition: service_started
      myapp:
        condition: service_started

networks:
  final:
    external:
      name: final