pipeline {
    agent any
    stages {
        stage("Setup environment and run tests") {
            steps {
                docker.image('selenoid/chrome:99.0')
                step([$class: 'DockerComposeBuilder', dockerComposeFile: './final_project/docker-compose.yml', option: [$class: 'StartAllServices'], useCustomDockerComposeFile: true])
            }
        }
        stage('Reports') {
            steps {
                script {
                    bat 'docker wait tests'
                }
                allure([
      	            results: [[path: './final_project/allure-results']]
                ])
  	        }
        }
        stage("Teardown environment") {
            steps {
                cleanWs()
//              step([$class: 'DockerComposeBuilder', dockerComposeFile: './final_project/docker-compose.yml', option: [$class: 'StopAllServices'], useCustomDockerComposeFile: true])
            }
        }
    }
}