pipeline {
    agent any
    stages {
        stage("Setup environment and run tests") {
            steps {
                step([$class: 'DockerComposeBuilder', dockerComposeFile: './final_project/docker-compose.yml', option: [$class: 'StartAllServices'], useCustomDockerComposeFile: true])
            }
        }
        stage('Reports') {
            steps {
                script {
                    bat 'docker wait ui-tests'
                }
                allure([
      	            includeProperties: false,
      	            jdk: '',
      	            properties: [],
      	            reportBuildPolicy: 'ALWAYS',
      	            results: [[path: './final_project/allure-report']]
                ])
  	        }
        }
        stage("Teardown environment") {
            steps {
                cleanWs()
//              step([$class: 'DockerComposeBuilder', dockerComposeFile: './final_project/docker-compose.yml', option: [$class: 'StopAllServices'], useCustomDockerComposeFile: true])
            }
        }
    }
}